const users = [
  { username: "user1", password: "password1" },
  { username: "user2", password: "password2" },
  { username: "user3", password: "password3" },
];
// I'm not sure how to get to the direct image?
// maybe like 'https://google.com/frog_figurine1.jpeg'
// anyone know?
const products = [
  {
    name: "Frog Figurine 1",
    description: "A cute frog rubbing its belly",
    price: 10.99,
    image: "frog_figurine_1.jpeg",
    inventory: 10,
    category: "Figurines",
  },
  {
    name: "Frog Figurine 2",
    description: "A small terrifying frog/blobfish figurine",
    price: 8.99,
    image: "frog_figurine_2.jpeg",
    inventory: 5,
    category: "Figurines",
  },
  {
    name: "Frog Figurine 3",
    description: "A large frog sitting frog style",
    price: 15.99,
    image: "frog_figurine_2.jpeg",
    inventory: 5,
    category: "Figurines",
  },
  {
    name: "Frog Figurine 4",
    description: "A small ballerina frog",
    price: 12.99,
    image: "frog_figurine_2.jpeg",
    inventory: 5,
    category: "Figurines",
  },
  {
    name: "Frog Art 1",
    description: "An artistic frog painting",
    price: 29.99,
    image: "frog_art_1.jpeg",
    inventory: 3,
    category: "Artwork",
  },
  {
    name: "Frog Art 2",
    description: "A frog painting down by the bayou",
    price: 39.99,
    image: "frog_art_2.jpeg",
    inventory: 2,
    category: "Artwork",
  },
  {
    name: "Frog Art 3",
    description: "Psychedelic frog art",
    price: 27.99,
    image: "frog_art_2.jpeg",
    inventory: 2,
    category: "Artwork",
  },
  {
    name: "Frog Art 4",
    description: "A wrinkled frog with a hat",
    price: 22.99,
    image: "frog_art_2.jpeg",
    inventory: 2,
    category: "Artwork",
  },
  {
    name: "Frog Art 5",
    description: "A canvas print of a colorful frog on a mushroom",
    price: 44.95,
    image: "frog_art_2.jpeg",
    inventory: 2,
    category: "Artwork",
  },
  {
    name: "Frog Art 7",
    description: "Artwork featuring a frog with a robe",
    price: 17.99,
    image: "frog_art_2.jpeg",
    inventory: 2,
    category: "Artwork",
  },
  {
    name: "Frog Suit",
    description: "Green frog-themed costume",
    price: 39.99,
    image: "frog_suit.jpeg",
    inventory: 10,
    category: "Clothing",
  },
  {
    name: "Frog Dress",
    description: "Stylish frog-patterned dress",
    price: 29.99,
    image: "frog_dress.jpeg",
    inventory: 6,
    category: "Clothing",
  },
  {
    name: "Frog Dress 2",
    description: "kermit the frog-themed gown",
    price: 49.99,
    image: "frog_dress_2.jpeg",
    inventory: 3,
    category: "Clothing",
  },
  {
    name: "Frog Jacket",
    description: "Warm frog-printed jacket",
    price: 79.99,
    image: "frog_jacket.jpeg",
    inventory: 5,
    category: "Clothing",
  },
  {
    name: "Frog Hoodie",
    description: "Cozy frog-themed hoodie",
    price: 59.99,
    image: "frog_hoodie.jpeg",
    inventory: 7,
    category: "Clothing",
  },
  {
    name: "Frog Shirt 1",
    description: "Casual I like frog shirt",
    price: 19.99,
    image: "frog_shirt_1.jpeg",
    inventory: 12,
    category: "Clothing",
  },
  {
    name: "Frog Shirt 2",
    description: "Graphic saxafrog t-shirt",
    price: 14.99,
    image: "frog_shirt_2.jpeg",
    inventory: 8,
    category: "Clothing",
  },
  {
    name: "Frog Shirt 3",
    description: "Frog lover's tshirt",
    price: 17.99,
    image: "frog_shirt_3.jpeg",
    inventory: 9,
    category: "Clothing",
  },
  {
    name: "Frog Shirt 4",
    description: "only frogs shirt",
    price: 16.99,
    image: "frog_shirt_4.jpeg",
    inventory: 6,
    category: "Clothing",
  },
  {
    name: "Frog Hat 1",
    description: "Stylish frog-themed hat",
    price: 9.99,
    image: "frog_hat_1.jpeg",
    inventory: 15,
    category: "Accessories",
  },
  {
    name: "Frog Hat 2",
    description: "Embroidered frog cap",
    price: 12.99,
    image: "frog_hat_2.jpeg",
    inventory: 11,
    category: "Accessories",
  },
  {
    name: "Frog Hat 3",
    description: "Funny frog beanie",
    price: 11.99,
    image: "frog_hat_3.jpeg",
    inventory: 13,
    category: "Accessories",
  },
  {
    name: "Frog Hat 4",
    description: "Frog-themed sun hat",
    price: 14.99,
    image: "frog_hat_4.jpeg",
    inventory: 9,
    category: "Accessories",
  },
  {
    name: "Frog Plate 1",
    description: "Frog-shaped decorative plate",
    price: 24.99,
    image: "frog_plate_1.jpeg",
    inventory: 5,
    category: "Home Decor",
  },
  {
    name: "Frog Plate 2",
    description: "Colorful frog-printed plate",
    price: 19.99,
    image: "frog_plate_2.jpeg",
    inventory: 8,
    category: "Home Decor",
  },
  {
    name: "Frog Plate 3",
    description: "Ceramic frog dish",
    price: 14.99,
    image: "frog_plate_3.jpeg",
    inventory: 10,
    category: "Home Decor",
  },
  {
    name: "Frog Plate 4",
    description: "Frog-themed serving platter",
    price: 29.99,
    image: "frog_plate_4.jpeg",
    inventory: 6,
    category: "Home Decor",
  },
  {
    name: "Frog Cup 1",
    description: "Cute frog-shaped mug",
    price: 12.99,
    image: "frog_cup_1.jpeg",
    inventory: 12,
    category: "Home Decor",
  },
  {
    name: "Frog Cup 2",
    description: "Colorful frog-printed cup",
    price: 9.99,
    image: "frog_cup_2.jpeg",
    inventory: 15,
    category: "Home Decor",
  },
  {
    name: "Frog Cup 3",
    description: "Frog-themed coffee cup",
    price: 11.99,
    image: "frog_cup_3.jpeg",
    inventory: 13,
    category: "Home Decor",
  },
  {
    name: "Frog Cup 4",
    description: "Whimsical frog-patterned mug",
    price: 14.99,
    image: "frog_cup_4.jpeg",
    inventory: 9,
    category: "Home Decor",
  },

  // please help!  :)  we need hundreds, I started with the ones we have images for
];

const orders = [
  { user_id: 1, totalPrice: 30, status: true },
  { user_id: 2, totalPrice: 15, status: false },
  // can add more
];

const lineItems = [
  { order_id: 1, product_id: 1, quantity: 2 },
  { order_id: 1, product_id: 2, quantity: 1 },
  { order_id: 2, product_id: 2, quantity: 3 },
  // we can adjust as we want of course
];

module.exports = { users, products, orders, lineItems };
